#!/usr/bin/env bash
# Build the Rust JNI library and standalone native Android preview APK.
# Run inside `nix develop`: tool/build-native-android.sh [--release]
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
MODE="${1:---debug}"

case "$MODE" in
  --debug) GRADLE_TASKS=(testDebugUnitTest lintDebug assembleDebug); APK_VARIANT=debug ;;
  --release) GRADLE_TASKS=(assembleRelease); APK_VARIANT=release ;;
  *) echo "usage: $0 [--debug|--release]" >&2; exit 2 ;;
esac

# Debug-only hook for the Lightning Address end-to-end smoke test: setting both
# PYX_LNADDR_DEBUG_ORIGIN and PYX_LNADDR_DEBUG_DOMAIN bakes a locally run
# lnaddrd in place of the wallet's built-in server (see
# rust/src/lnaddr/discovery.rs and docs/native-android/lnaddr-smoke.md). The
# cargo feature that reads them is refused for --release, so a release artifact
# can carry neither the override nor the code that reads it. Checked before any
# build step so a mistake fails immediately.
CARGO_FEATURES="android-jni"
if [[ -n "${PYX_LNADDR_DEBUG_ORIGIN:-}" || -n "${PYX_LNADDR_DEBUG_DOMAIN:-}" ]]; then
  if [[ "$MODE" == "--release" ]]; then
    echo "PYX_LNADDR_DEBUG_ORIGIN/PYX_LNADDR_DEBUG_DOMAIN cannot be used with --release" >&2
    exit 1
  fi
  if [[ -z "${PYX_LNADDR_DEBUG_ORIGIN:-}" || -z "${PYX_LNADDR_DEBUG_DOMAIN:-}" ]]; then
    echo "PYX_LNADDR_DEBUG_ORIGIN and PYX_LNADDR_DEBUG_DOMAIN must be set together" >&2
    exit 1
  fi
  CARGO_FEATURES="$CARGO_FEATURES,lnaddr-debug-server"
  echo "WARNING: baking debug lnaddrd override $PYX_LNADDR_DEBUG_ORIGIN ($PYX_LNADDR_DEBUG_DOMAIN)" >&2
fi

JNI_ROOT="$ROOT/android-native/app/src/main/jniLibs"
RUST_OUT="$ROOT/build/native-rust"
TARGETS=(arm64-v8a)
if [[ "${PYX_ABI_X86_64:-0}" == "1" ]]; then
  TARGETS+=(x86_64)
fi
NDK_ARGS=()
for target in "${TARGETS[@]}"; do
  NDK_ARGS+=(-t "$target")
done

mkdir -p "$JNI_ROOT" "$RUST_OUT"

# jniLibs is generated by this script. Remove only the artifacts we own so a
# previous optional emulator build cannot leak x86_64 into an arm64 release.
rm -f \
  "$JNI_ROOT/arm64-v8a/libpyx.so" \
  "$JNI_ROOT/arm64-v8a/libc++_shared.so" \
  "$JNI_ROOT/x86_64/libpyx.so" \
  "$JNI_ROOT/x86_64/libc++_shared.so"

echo "Building Rust JNI library for ${TARGETS[*]}"
(
  cd "$ROOT/rust"
  export RUSTFLAGS="${RUSTFLAGS:-} -C link-arg=-Wl,-z,max-page-size=16384"
  cargo ndk --platform 24 "${NDK_ARGS[@]}" -o "$RUST_OUT" \
    build --locked --release --no-default-features --features "$CARGO_FEATURES"
)

# Keep libconduit.so for the Flutter oracle. The native preview loads libpyx,
# so package the same JNI-enabled artifact under its native-only library name.
for abi in "${TARGETS[@]}"; do
  mkdir -p "$JNI_ROOT/$abi"
  install -m 0644 "$RUST_OUT/$abi/libconduit.so" "$JNI_ROOT/$abi/libpyx.so"
  case "$abi" in
    arm64-v8a) NDK_TRIPLE="aarch64-linux-android" ;;
    x86_64) NDK_TRIPLE="x86_64-linux-android" ;;
    *) echo "no NDK C++ runtime mapping for ABI: $abi" >&2; exit 1 ;;
  esac
  CXX_SHARED="$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/$NDK_TRIPLE/libc++_shared.so"
  if [[ ! -f "$CXX_SHARED" ]]; then
    echo "NDK C++ shared runtime is missing for $abi: $CXX_SHARED" >&2
    exit 1
  fi
  # libpyx links the NDK shared C++ runtime through transitive native
  # dependencies. Android does not provide this library, so it must travel in
  # the APK for System.loadLibrary("pyx") to succeed on a clean device.
  install -m 0644 "$CXX_SHARED" "$JNI_ROOT/$abi/libc++_shared.so"
  if ! "$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-readelf" \
      -d "$JNI_ROOT/$abi/libpyx.so" | grep -F 'Shared library: [libc++_shared.so]' >/dev/null; then
    echo "$abi/libpyx.so no longer declares its packaged libc++_shared.so dependency" >&2
    exit 1
  fi
  if [[ "$MODE" == "--release" ]]; then
    SYMBOL_DIR="$ROOT/build/native-symbols/$abi"
    mkdir -p "$SYMBOL_DIR"
    install -m 0644 "$JNI_ROOT/$abi/libpyx.so" "$SYMBOL_DIR/libpyx.so"
    "$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip" \
      --strip-unneeded "$JNI_ROOT/$abi/libpyx.so"
  fi

  # Every PT_LOAD segment must be compatible with Android's 16 KiB page-size
  # devices. Checking the final copied library catches linker/configuration
  # regressions before Gradle packages an otherwise installable-looking APK.
  for native_library in libpyx.so libc++_shared.so; do
    if ! "$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-readelf" \
      -lW "$JNI_ROOT/$abi/$native_library" | awk '
        $1 == "LOAD" {
          seen = 1
          alignment = $NF
          sub(/^0x/, "", alignment)
          if (strtonum("0x" alignment) < 16384) bad = 1
        }
        END { exit !(seen && !bad) }
      '; then
      echo "$abi/$native_library is not 16 KiB page aligned" >&2
      exit 1
    fi
  done
done

echo "Building native Android APK (${GRADLE_TASKS[*]})"
GRADLE_ARGS=()
for task in "${GRADLE_TASKS[@]}"; do
  GRADLE_ARGS+=(":app:$task")
done
gradle -p "$ROOT/android-native" "${GRADLE_ARGS[@]}"

APK="$ROOT/android-native/app/build/outputs/apk/$APK_VARIANT/app-$APK_VARIANT.apk"
for native_library in libpyx.so libc++_shared.so; do
  if ! jar tf "$APK" | grep -Fx "lib/arm64-v8a/$native_library" >/dev/null; then
    echo "native APK is missing lib/arm64-v8a/$native_library" >&2
    exit 1
  fi
done
if [[ "${PYX_ABI_X86_64:-0}" == "1" ]]; then
  for native_library in libpyx.so libc++_shared.so; do
    if ! jar tf "$APK" | grep -Fx "lib/x86_64/$native_library" >/dev/null; then
      echo "native APK is missing requested lib/x86_64/$native_library" >&2
      exit 1
    fi
  done
  if jar tf "$APK" | grep -E '^lib/(armeabi-v7a|x86)/' >/dev/null; then
    echo "native APK contains an unsupported 32-bit ABI" >&2
    exit 1
  fi
elif jar tf "$APK" | grep '^lib/x86_64/libpyx\.so$' >/dev/null; then
  echo "arm64 native APK unexpectedly contains lib/x86_64/libpyx.so" >&2
  exit 1
elif jar tf "$APK" | grep -E '^lib/(armeabi-v7a|x86|x86_64)/' >/dev/null; then
  echo "arm64 native APK contains an unexpected secondary ABI" >&2
  exit 1
fi
PACKAGED_ABIS="$(jar tf "$APK" | awk -F/ '/^lib\/[^/]+\/.*\.so$/ { print $2 }' | sort -u)"
EXPECTED_ABIS="$(printf '%s\n' "${TARGETS[@]}" | sort -u)"
if [[ "$PACKAGED_ABIS" != "$EXPECTED_ABIS" ]]; then
  echo "native APK ABI set is not exact (expected: ${EXPECTED_ABIS//$'\n'/, }; packaged: ${PACKAGED_ABIS//$'\n'/, })" >&2
  exit 1
fi
if jar tf "$APK" | grep -E 'libflutter\.so|flutter_assets|libconduit\.so' >/dev/null; then
  echo "native APK unexpectedly contains Flutter/legacy bridge artifacts" >&2
  exit 1
fi


BUILD_TOOLS_ROOT="${ANDROID_SDK_ROOT:-${ANDROID_HOME:-}}/build-tools"
BUILD_TOOLS_DIR=""
for candidate in "$BUILD_TOOLS_ROOT"/*; do
  if [[ -x "$candidate/zipalign" && -x "$candidate/apksigner" && -x "$candidate/aapt" ]]; then
    BUILD_TOOLS_DIR="$candidate"
  fi
done
if [[ -z "$BUILD_TOOLS_DIR" ]]; then
  echo "Android build-tools with zipalign, apksigner and aapt are required for APK certification" >&2
  exit 1
fi
ZIPALIGN="$BUILD_TOOLS_DIR/zipalign"
APKSIGNER="$BUILD_TOOLS_DIR/apksigner"
AAPT="$BUILD_TOOLS_DIR/aapt"
"$ZIPALIGN" -c -P 16 -v 4 "$APK" >/dev/null
"$APKSIGNER" verify --verbose "$APK" >/dev/null
if ! "$AAPT" dump xmltree "$APK" AndroidManifest.xml | \
    grep -E 'android:usesCleartextTraffic.*0x0$' >/dev/null; then
  echo "native APK does not explicitly disable cleartext traffic" >&2
  exit 1
fi
if [[ "$MODE" == "--release" ]]; then
  if ! "$AAPT" dump badging "$APK" | grep -q "^package: name='cash.pyx.app'"; then
    echo "release APK does not use the production cash.pyx.app identity" >&2
    exit 1
  fi
  if "$AAPT" dump xmltree "$APK" AndroidManifest.xml | \
      grep -E 'android:debuggable.*0xffffffff' >/dev/null; then
    echo "release APK is debuggable" >&2
    exit 1
  fi
  "$APKSIGNER" verify --print-certs "$APK"
fi

echo "Built $APK"
